// <auto-generated />
using System;
using Feedback_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Feedback_API.Migrations
{
    [DbContext(typeof(FeedbackContext))]
    [Migration("20200501163430_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Feedback_API.Models.Domain.OpeningTime", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("Close")
                        .HasColumnType("time(6)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Open")
                        .HasColumnType("time(6)");

                    b.Property<long>("PlaceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PlaceID");

                    b.ToTable("openingtimes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Close = new TimeSpan(0, 20, 0, 0, 0),
                            Day = 0,
                            Open = new TimeSpan(0, 8, 0, 0, 0),
                            PlaceID = 2L
                        },
                        new
                        {
                            ID = 2L,
                            Close = new TimeSpan(0, 19, 0, 0, 0),
                            Day = 0,
                            Open = new TimeSpan(0, 9, 0, 0, 0),
                            PlaceID = 3L
                        },
                        new
                        {
                            ID = 3L,
                            Close = new TimeSpan(0, 22, 0, 0, 0),
                            Day = 0,
                            Open = new TimeSpan(0, 10, 0, 0, 0),
                            PlaceID = 1L
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Place", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("PlaceTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("PlaceTypeID");

                    b.ToTable("places");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            IsVerified = true,
                            Name = "Coffeehut",
                            PlaceTypeID = 1L,
                            Street = "City Street 1",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 2L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            IsVerified = true,
                            Name = "Footly",
                            PlaceTypeID = 2L,
                            Street = "City Street 2",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 3L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            IsVerified = true,
                            Name = "Gusto Generic",
                            PlaceTypeID = 3L,
                            Street = "City Street 3",
                            ZipCode = "3500"
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.PlaceImage", b =>
                {
                    b.Property<long>("PlaceID")
                        .HasColumnType("bigint");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("URI")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlaceID", "ID");

                    b.ToTable("PlaceImages");
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.PlaceOwner", b =>
                {
                    b.Property<long>("PlaceID")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerID")
                        .HasColumnType("bigint");

                    b.HasKey("PlaceID", "OwnerID");

                    b.ToTable("placeowner");

                    b.HasData(
                        new
                        {
                            PlaceID = 1L,
                            OwnerID = 1L
                        },
                        new
                        {
                            PlaceID = 2L,
                            OwnerID = 2L
                        },
                        new
                        {
                            PlaceID = 3L,
                            OwnerID = 3L
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.PlaceType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("placetypes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "Café"
                        },
                        new
                        {
                            ID = 2L,
                            Name = "Shoe Store"
                        },
                        new
                        {
                            ID = 3L,
                            Name = "Fast Food Restaurant"
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Reaction", b =>
                {
                    b.Property<long>("ReviewID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ReviewID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("reactions");

                    b.HasData(
                        new
                        {
                            ReviewID = 2L,
                            UserID = 3L,
                            IsHelpful = false
                        },
                        new
                        {
                            ReviewID = 1L,
                            UserID = 2L,
                            IsHelpful = true
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Review", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PlaceID")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PlaceID");

                    b.HasIndex("UserID");

                    b.ToTable("reviews");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            PlaceID = 2L,
                            Rating = 2,
                            Text = "meh",
                            Time = new DateTime(2020, 5, 1, 18, 34, 29, 716, DateTimeKind.Local).AddTicks(9993),
                            UserID = 2L
                        },
                        new
                        {
                            ID = 2L,
                            PlaceID = 1L,
                            Rating = 5,
                            Text = "nice",
                            Time = new DateTime(2020, 5, 1, 18, 34, 29, 719, DateTimeKind.Local).AddTicks(3812),
                            UserID = 1L
                        },
                        new
                        {
                            ID = 3L,
                            PlaceID = 1L,
                            Rating = 4,
                            Text = "pretty good",
                            Time = new DateTime(2020, 5, 1, 18, 34, 29, 719, DateTimeKind.Local).AddTicks(3861),
                            UserID = 2L
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarURI")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            FirstName = "Peter",
                            IsVerified = false,
                            LastName = "Gustav",
                            PasswordHash = new byte[] { 112, 208, 7, 234, 45, 84, 135, 62, 206, 208, 196, 41, 205, 86, 201, 2, 150, 39, 254, 198, 149, 231, 165, 118, 25, 98, 52, 184, 174, 161, 59, 98, 120, 135, 100, 68, 139, 239, 167, 249, 114, 101, 194, 47, 152, 70, 212, 132, 212, 131, 184, 157, 36, 96, 153, 246, 205, 7, 98, 129, 29, 255, 51, 200 },
                            PasswordSalt = new byte[] { 223, 144, 34, 59, 104, 179, 34, 218, 71, 99, 55, 191, 106, 137, 58, 208, 159, 35, 211, 221, 110, 36, 231, 49, 98, 1, 179, 53, 153, 43, 77, 195, 146, 253, 26, 193, 146, 21, 49, 218, 193, 8, 195, 81, 64, 145, 44, 250, 3, 168, 26, 65, 200, 37, 191, 131, 29, 113, 29, 230, 2, 218, 160, 171, 197, 116, 107, 117, 224, 197, 95, 46, 137, 152, 250, 5, 156, 132, 51, 245, 66, 130, 173, 59, 60, 109, 56, 94, 72, 210, 22, 176, 49, 177, 131, 238, 93, 198, 168, 84, 10, 232, 111, 98, 83, 169, 90, 90, 25, 174, 119, 236, 38, 55, 121, 43, 253, 165, 90, 6, 194, 153, 228, 234, 162, 99, 118, 211 },
                            Role = "User",
                            Street = "Example Street 1",
                            Username = "pete",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 2L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            FirstName = "John",
                            IsVerified = false,
                            LastName = "Gustav",
                            PasswordHash = new byte[] { 95, 53, 140, 58, 67, 233, 173, 54, 129, 157, 63, 141, 147, 75, 69, 180, 22, 32, 251, 32, 53, 28, 57, 209, 31, 65, 109, 197, 222, 94, 89, 16, 184, 3, 17, 1, 202, 105, 18, 135, 198, 97, 193, 162, 123, 1, 32, 31, 108, 197, 74, 180, 197, 193, 152, 229, 63, 45, 92, 175, 245, 38, 234, 196 },
                            PasswordSalt = new byte[] { 50, 14, 87, 72, 22, 52, 1, 67, 114, 89, 28, 240, 107, 204, 68, 213, 169, 205, 36, 100, 161, 243, 181, 51, 48, 84, 228, 161, 207, 2, 112, 180, 203, 255, 163, 137, 160, 28, 45, 27, 249, 60, 212, 97, 55, 154, 175, 239, 225, 163, 234, 98, 208, 212, 228, 193, 254, 172, 184, 26, 68, 169, 62, 83, 58, 93, 160, 207, 91, 157, 6, 149, 248, 15, 71, 102, 252, 123, 171, 4, 175, 52, 37, 182, 215, 79, 144, 17, 102, 53, 83, 235, 78, 111, 153, 200, 25, 193, 208, 146, 98, 205, 127, 234, 172, 216, 47, 39, 32, 160, 243, 224, 133, 104, 205, 23, 171, 248, 175, 186, 199, 186, 69, 247, 166, 239, 73, 1 },
                            Role = "User",
                            Street = "Example Street 2",
                            Username = "MrJohn",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 3L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            FirstName = "Heinz",
                            IsVerified = false,
                            LastName = "Gustav",
                            PasswordHash = new byte[] { 159, 216, 253, 149, 132, 80, 80, 0, 169, 3, 4, 158, 251, 4, 127, 5, 232, 116, 122, 183, 20, 166, 45, 199, 44, 168, 75, 158, 135, 247, 246, 16, 189, 39, 140, 243, 205, 57, 20, 48, 66, 175, 46, 154, 41, 215, 95, 194, 15, 111, 226, 148, 96, 59, 220, 204, 122, 22, 204, 143, 183, 190, 116, 248 },
                            PasswordSalt = new byte[] { 115, 148, 241, 157, 56, 22, 224, 68, 28, 173, 124, 250, 2, 79, 146, 231, 13, 20, 171, 10, 243, 200, 190, 170, 10, 105, 212, 70, 145, 55, 153, 219, 191, 143, 195, 192, 169, 49, 21, 234, 244, 219, 81, 13, 1, 188, 17, 58, 232, 54, 28, 10, 125, 85, 20, 138, 116, 224, 247, 226, 62, 91, 133, 90, 50, 41, 223, 226, 108, 177, 138, 24, 172, 85, 40, 126, 155, 73, 242, 110, 231, 122, 167, 153, 48, 238, 14, 221, 251, 227, 229, 13, 133, 119, 128, 56, 112, 150, 61, 129, 204, 161, 33, 222, 48, 41, 98, 93, 106, 99, 45, 202, 221, 223, 57, 95, 78, 66, 134, 149, 190, 227, 148, 255, 185, 240, 31, 17 },
                            Role = "User",
                            Street = "Example Street 3",
                            Username = "Ketchup",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 4L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            FirstName = "Olaf",
                            IsVerified = false,
                            LastName = "Gustav",
                            PasswordHash = new byte[] { 58, 177, 128, 191, 78, 141, 222, 165, 128, 160, 208, 172, 46, 43, 93, 176, 94, 117, 104, 177, 170, 55, 249, 102, 89, 192, 117, 214, 70, 245, 26, 45, 61, 157, 159, 36, 82, 62, 112, 211, 200, 252, 4, 25, 103, 126, 5, 169, 148, 202, 9, 215, 247, 224, 248, 1, 255, 114, 16, 214, 95, 216, 143, 239 },
                            PasswordSalt = new byte[] { 2, 247, 189, 255, 52, 19, 7, 181, 207, 108, 167, 186, 248, 198, 212, 173, 185, 91, 123, 234, 39, 205, 193, 194, 139, 30, 30, 123, 30, 62, 243, 195, 109, 29, 70, 139, 170, 22, 241, 32, 208, 230, 14, 241, 23, 165, 77, 130, 5, 58, 112, 64, 216, 133, 95, 252, 21, 113, 59, 171, 194, 227, 66, 53, 166, 163, 107, 45, 232, 78, 204, 189, 196, 100, 192, 12, 247, 17, 74, 23, 91, 149, 236, 158, 193, 175, 205, 87, 137, 62, 218, 22, 130, 91, 223, 167, 54, 186, 179, 158, 43, 130, 72, 16, 39, 108, 45, 19, 210, 30, 6, 30, 113, 194, 147, 8, 47, 56, 207, 253, 119, 164, 56, 34, 22, 177, 191, 172 },
                            Role = "User",
                            Street = "Example Street 4",
                            Username = "Olaf",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 5L,
                            City = "Krems an der Donau",
                            Country = "AT",
                            FirstName = "Hans",
                            IsVerified = false,
                            LastName = "Gustav",
                            PasswordHash = new byte[] { 18, 214, 200, 155, 234, 204, 230, 254, 245, 9, 182, 48, 161, 36, 236, 160, 91, 150, 50, 125, 241, 92, 14, 5, 207, 87, 86, 251, 33, 221, 71, 38, 250, 87, 66, 121, 143, 219, 169, 213, 224, 122, 105, 25, 47, 245, 107, 36, 8, 197, 131, 186, 185, 114, 254, 153, 125, 165, 14, 181, 149, 115, 38, 238 },
                            PasswordSalt = new byte[] { 61, 230, 178, 108, 25, 97, 189, 30, 79, 26, 74, 81, 83, 93, 111, 136, 15, 137, 140, 254, 103, 107, 40, 244, 29, 100, 175, 178, 57, 111, 6, 91, 203, 200, 26, 236, 160, 25, 88, 24, 44, 70, 242, 111, 88, 114, 10, 176, 230, 133, 86, 103, 216, 126, 123, 15, 207, 34, 9, 162, 22, 196, 254, 8, 42, 29, 64, 3, 77, 79, 203, 225, 25, 13, 58, 214, 200, 144, 76, 138, 108, 210, 59, 85, 29, 61, 54, 29, 89, 142, 113, 31, 63, 141, 183, 1, 197, 202, 1, 123, 139, 21, 34, 18, 73, 111, 48, 178, 45, 66, 74, 253, 139, 36, 26, 124, 249, 72, 172, 77, 158, 139, 234, 112, 68, 228, 17, 105 },
                            Role = "User",
                            Street = "Example Street 5",
                            Username = "hansi12",
                            ZipCode = "3500"
                        },
                        new
                        {
                            ID = 6L,
                            City = "localhost",
                            Country = "yes",
                            FirstName = "Bobby",
                            IsVerified = false,
                            LastName = "Tables",
                            PasswordHash = new byte[] { 118, 99, 98, 182, 222, 183, 195, 234, 172, 163, 240, 224, 176, 21, 209, 197, 72, 136, 166, 213, 230, 157, 137, 165, 127, 138, 43, 104, 228, 105, 31, 127, 43, 228, 60, 11, 29, 25, 139, 27, 159, 231, 85, 164, 201, 21, 126, 181, 231, 176, 28, 24, 224, 73, 38, 181, 24, 76, 242, 102, 248, 248, 66, 186 },
                            PasswordSalt = new byte[] { 67, 170, 178, 176, 218, 188, 169, 213, 47, 203, 17, 86, 215, 62, 108, 152, 195, 54, 158, 139, 243, 110, 114, 217, 239, 60, 148, 205, 207, 32, 200, 33, 205, 21, 218, 86, 129, 66, 132, 194, 218, 184, 88, 126, 253, 58, 213, 6, 222, 32, 95, 84, 227, 56, 97, 158, 37, 149, 41, 216, 83, 25, 127, 78, 144, 97, 30, 152, 168, 82, 187, 122, 158, 12, 190, 197, 162, 227, 239, 78, 147, 77, 137, 65, 243, 168, 37, 230, 233, 120, 187, 139, 255, 56, 160, 178, 233, 224, 112, 101, 89, 11, 124, 107, 211, 97, 76, 9, 132, 51, 35, 64, 72, 182, 132, 62, 103, 1, 112, 17, 124, 20, 59, 139, 130, 183, 126, 119 },
                            Role = "Admin",
                            Street = "443",
                            Username = "admin",
                            ZipCode = "1337"
                        });
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.OpeningTime", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.Place", "Place")
                        .WithMany("OpeningTimes")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Place", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.PlaceType", "PlaceType")
                        .WithMany("Places")
                        .HasForeignKey("PlaceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.PlaceImage", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.Place", "Place")
                        .WithMany("Images")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.PlaceOwner", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.Place", "Place")
                        .WithMany("PlaceOwners")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Reaction", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.Review", "Review")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedback_API.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback_API.Models.Domain.Review", b =>
                {
                    b.HasOne("Feedback_API.Models.Domain.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedback_API.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
